# Generated by Django 3.2.9 on 2021-12-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Язык программирования', 'verbose_name_plural': 'Языки программирования'},
        ),
    ]
